#!/usr/bin/env python3
"""
Sync local Claude usage to Git repository

Created & Directed by Bohee Lee
https://github.com/bohee-connectome

Built with Claude Code
"""

import os
import sys
import json
import socket
import subprocess
from pathlib import Path
from datetime import datetime, timezone

# Configuration file
CONFIG_FILE = Path.home() / ".claude" / "usage_sync_config.json"

def load_config():
    """Load sync configuration"""
    if not CONFIG_FILE.exists():
        return None

    with open(CONFIG_FILE, 'r') as f:
        return json.load(f)

def save_config(config):
    """Save sync configuration"""
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=2)

def setup_repo():
    """Setup Git repository for usage tracking"""
    print("=" * 70)
    print("🔧 Git Repository Setup")
    print("=" * 70)
    print()
    print("You need a Git repository to store usage data from all devices.")
    print()
    print("Options:")
    print("  1. Create a new GitHub repo (recommended: private repo)")
    print("  2. Use existing Git repo")
    print()

    repo_path = input("Enter local path for the repo (e.g., ~/claude-usage-tracker): ").strip()

    if not repo_path:
        print("❌ No path provided")
        sys.exit(1)

    repo_path = Path(repo_path).expanduser().absolute()

    # Check if repo exists
    if not repo_path.exists():
        print(f"\n📁 Creating directory: {repo_path}")
        repo_path.mkdir(parents=True, exist_ok=True)

        # Initialize git
        print("🔧 Initializing Git repository...")
        subprocess.run(['git', 'init'], cwd=repo_path, check=True)

        # Create data directory
        data_dir = repo_path / "data"
        data_dir.mkdir(exist_ok=True)

        # Create README
        readme = repo_path / "README.md"
        readme.write_text("""# Claude Usage Tracker

Multi-device Claude usage tracking via Git.

## Structure

```
data/
  device-name-1.json
  device-name-2.json
  ...
```

## Usage

On each device:
```bash
ccusage-sync    # Export and push usage data
ccusage-total   # Pull and show combined usage
```

Generated by Claude Code.
""")

        subprocess.run(['git', 'add', '.'], cwd=repo_path, check=True)
        subprocess.run(
            ['git', 'commit', '-m', 'Initial commit: Setup usage tracker'],
            cwd=repo_path,
            check=True
        )

        print("\n✅ Repository initialized!")
        print()
        print("📝 Next steps:")
        print("  1. Create a GitHub repo (can be private)")
        print("  2. Add remote: git remote add origin <your-repo-url>")
        print("  3. Push: git push -u origin main")
        print()
        input("Press Enter after setting up remote...")

    # Save config
    config = {
        'repo_path': str(repo_path),
        'data_dir': str(repo_path / "data"),
        'setup_date': datetime.now(timezone.utc).isoformat()
    }

    save_config(config)

    print()
    print(f"✅ Configuration saved!")
    print(f"📁 Repo: {repo_path}")

    return config

def sync_usage():
    """Export usage and sync to Git"""
    # Load config
    config = load_config()

    if not config:
        print("⚙️  First time setup required")
        print()
        config = setup_repo()

    repo_path = Path(config['repo_path'])
    data_dir = Path(config['data_dir'])

    if not repo_path.exists():
        print(f"❌ Repository not found: {repo_path}")
        print()
        print("Run setup again:")
        print("  rm ~/.claude/usage_sync_config.json")
        print("  ccusage-sync")
        sys.exit(1)

    print("🚀 Syncing Claude usage...")
    print()

    # Export usage
    device_id = socket.gethostname().replace('.', '-').replace(' ', '-').lower()
    output_file = data_dir / f"{device_id}.json"

    print("📊 Exporting local usage...")
    result = subprocess.run(
        [sys.executable, str(Path(__file__).parent / 'export_usage.py'), str(output_file)],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print("❌ Export failed")
        print(result.stderr)
        sys.exit(1)

    print(result.stdout)

    # Git sync
    print("🔄 Syncing to Git...")

    try:
        # Pull latest
        subprocess.run(['git', 'pull', '--rebase'], cwd=repo_path, check=False)

        # Add changes
        subprocess.run(['git', 'add', 'data/'], cwd=repo_path, check=True)

        # Commit
        commit_msg = f"Update usage from {device_id} - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        result = subprocess.run(
            ['git', 'commit', '-m', commit_msg],
            cwd=repo_path,
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            print("✅ Changes committed")

            # Push
            push_result = subprocess.run(
                ['git', 'push'],
                cwd=repo_path,
                capture_output=True,
                text=True
            )

            if push_result.returncode == 0:
                print("✅ Pushed to remote")
            else:
                print("⚠️  Push failed (may need to set up remote)")
                print(push_result.stderr)
        else:
            if "nothing to commit" in result.stdout:
                print("ℹ️  No changes since last sync")
            else:
                print("⚠️  Commit failed")
                print(result.stderr)

    except subprocess.CalledProcessError as e:
        print(f"❌ Git operation failed: {e}")
        sys.exit(1)

    print()
    print("=" * 70)
    print("✅ Sync complete!")
    print()
    print("💡 To see combined usage from all devices:")
    print("   ccusage-total")
    print("=" * 70)

if __name__ == "__main__":
    sync_usage()
